trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-2019'
steps:
- checkout: self
  lfs: true
- task: UseDotNet@2
  displayName: install .NET Core SDK
  inputs:
    packageType: sdk
    version: 3.1.201
- task: UseDotNet@2
  displayName: install .NET Core SDK
  inputs:
    packageType: sdk
    version: 2.2.402
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    arguments: '-p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --no-build BomSweeper.Test'
- task: PublishCodeCoverageResults@1
  displayName: publish coverage report
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'BomSweeper.Test/coverage.cobertura.xml'
